services:
  - docker
before_install:
  - gem install bundler --pre
  - docker-compose build
script:
  - docker-compose up karma_ci
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker_trainings_aws"
  env: "DockerTrainingsAws-env"
  bucket_name: "elasticbeanstalk-eu-west-3-696051580433"
  bucket_path: "docker_trainings_aws"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master