version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '/app/node_modules'
      - '.:/app'
  unittest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9876:9876"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '/app/node_modules'
      - '.:/app'
    command: ["npm", "test"]